// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	ConfigConstant  *configConstant
	Customer        *customer
	CustomerAddress *customerAddress
	User            *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ConfigConstant = &Q.ConfigConstant
	Customer = &Q.Customer
	CustomerAddress = &Q.CustomerAddress
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		ConfigConstant:  newConfigConstant(db, opts...),
		Customer:        newCustomer(db, opts...),
		CustomerAddress: newCustomerAddress(db, opts...),
		User:            newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ConfigConstant  configConstant
	Customer        customer
	CustomerAddress customerAddress
	User            user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ConfigConstant:  q.ConfigConstant.clone(db),
		Customer:        q.Customer.clone(db),
		CustomerAddress: q.CustomerAddress.clone(db),
		User:            q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ConfigConstant:  q.ConfigConstant.replaceDB(db),
		Customer:        q.Customer.replaceDB(db),
		CustomerAddress: q.CustomerAddress.replaceDB(db),
		User:            q.User.replaceDB(db),
	}
}

type queryCtx struct {
	ConfigConstant  IConfigConstantDo
	Customer        ICustomerDo
	CustomerAddress ICustomerAddressDo
	User            IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ConfigConstant:  q.ConfigConstant.WithContext(ctx),
		Customer:        q.Customer.WithContext(ctx),
		CustomerAddress: q.CustomerAddress.WithContext(ctx),
		User:            q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
